apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  type: LoadBalancer   # Changed from NodePort to LoadBalancer
  ports:
  - port: 80           # External port
    targetPort: 3000   # Container's port
  selector:
    app: swiggy-app
